#  include the py files for the other Screens
#: import HomeScreen libs.main_screen.HomeScreen
#: import OTPVerificationScreen libs.main_screen.OTPVerificationScreen
#: import RegistrationCompleteScreen libs.main_screen.RegistrationCompleteScreen

#  include the kv files for the other Screens
#: include screens/home.kv
#: include screens/otp.kv
#: include screens/registration.kv


ScreenManager:
    HomeScreen:
    OTPVerificationScreen:
    RegistrationCompleteScreen:
